title: Matthew's Homepage
page-top-title: Matthew He
top-section-bg-text: The best way to predict the future is to invent it
home-subtitle: Matthew He
copyright-text: '&copy; Matthew He 2025-2026. All Rights Reserved.'